version: '3.1'
services:
  db:
    image: postgis/postgis:16-3.4 
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: foobar
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d


